name: 'Install'
description: 'Setup Node.js and install deps'

runs:
  using: composite
  steps:
    - name: Install PNPM
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        repository-url: 'https://registry.npmjs.org'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install
