name: Release
on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging, dev]
jobs:
  test-and-release:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Test project
        run: pnpm test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          dir: ./coverage/
          token: { { secrets.CODECOV_TOKEN } }
      - name: Release
        run: npx semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
