name: Quality

on:
  push:
    branches: [main, staging, dev]
  pull_request:
    branches: [main, staging, dev]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Install
        uses: .github/composite-actions/install

      - name: Build packages
        run: pnpm build

  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Install
        uses: .github/composite-actions/install

      - name: Run tests
        uses: pnpm test

    eslint:
      name: ESLint
      runs-on: ubuntu-20.04
      steps:
        - name: Checkout branch
          uses: actions/checkout@v3

        - name: Install
          uses: .github/composite-actions/install

        - name: Run ESLint
          run: pnpm lint

    types:
      name: TypeScript
      runs-on: ubuntu-20.04
      steps:
        - name: Checkout branch
          uses: actions/checkout@v3

        - name: Install
          uses: .github/composite-actions/install

        - name: Run typecheck
          run: pnpm typecheck

    prettier:
      name: Prettier
      runs-on: ubuntu-20.04
      steps:
        - name: Checkout branch
          uses: actions/checkout@v3

        - name: Install
          uses: .github/composite-actions/install

        - name: Run prettier
          run: pnpm format:check
