name: Release

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Install
        uses: ./.github/composite-actions/install
      - name: Build packages
        run: pnpm build
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
      - name: Release packages
        run: npx semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
